### ISSUE TITLE
Inline word count with other counts

### ISSUE THREAD

**Issue by JuroOravec** [cjwit/selection-word-count#1]
Thanks for the extension. The place where the count is display is somewhat impractical, as it's away from the rest of the navigation info (lines, row, chars).

Could the selected word count (red) be displayed inlined with other info (yellow)?

E.g. the two separate sidebar items `XX words selected` and `Ln YY, Col ZZZ (WW selected)` could be merged to `Ln YY, Col ZZZ (WW selected, XX words)`

<img width="1680" alt="Screenshot 2020-11-08 at 22 06 19" src="https://user-images.githubusercontent.com/25986782/98485582-63d9bd00-220f-11eb-9756-65345bdb5ba2.png">

**Comment by cjwit** [comment]
I like this idea, especially if it incorporates an overall word count functionality in a convenient way. (Something like `Ln WW, Col XX, YY words (ZZ selected)`.) I'm not sure when I'll get to it, but I'll try and take a look at some point.

**Comment by cjwit** [comment]
I added an overall word count into the extension and moved it to the right hand side of the status bar so that navigation is easier. This isn't exactly a solution to the issue (which would likely involve editing the "go to line" command display that has the other navigation info), but it does address the issue of navigation information being scattered across the status bar.

**Comment by JuroOravec** [comment]
Thanks for the update @cjwit! Yes, as you said, it's not quite the same, but adding the total count and moving the panel to right is a lot more intuitive, thanks for looking at this issue!

**Comment by cjwit** [comment]
This is my first extension and I really just did it for myself, but your comment was completely right! I like it much better. Thanks for taking the time to open the issue.
